### ISSUE TITLE
Support App Router without experimental.appDir in next.config.js

### ISSUE THREAD

**Issue by KokiSakano** [poteboy/kuma-ui#108]
In Next.js 13.4, The App Router is stable. Therefore, it is no longer necessary to experimental.appDir flag at next.config.js.
However, kuma-ui provides functionality in App Router based on that flag.

My ideal is using kuma-ui without having App Router information in `nextConfig` of `next.config.js`.

Do you have any immediate support plans for these?
if not, I would like to enable the functionality by checking the directory or by explicitly stating in `kumaConfig` that App Router is to be used to change the configuration.

**Comment by poteboy** [comment]
@KokiSakano 
Thanks for your issue! It seems this topic is already discussed in issue #97, which also deals with simplifying configurations for Kuma UI with Next.js. To keep things organized, I'll close this one as a duplicate. Please follow #97 for updates. And of course, if you'd like to take a crack at this, you're totally welcome to submit a PR 👍
