### ISSUE TITLE
How about creating a release note when pushing a git tag?

### ISSUE THREAD

**Issue by u-yas** [poteboy/kuma-ui#199]
Congratulations on the release of version 1!

In this issue, I propose to create a release note at the same time when you push a git tag.

Currently, only git tags are pushed to the kuma-ui repository, but by publishing release notes, people who follow the poteboy github user account will be able to know about new version releases on their github home page.

- By publishing a release note, people who follow your github user account will be able to know immediately on their github home page that you have released a new version.
※ I know that v1 of kuma-ui has been released is your tweet.

- The release note shows a large list of users who have contributed to your PR, and you can show your contribution to kuma-ui to people all over the world.

The changeset/action option for these automatic releases is on by default, so you may need to do some modification in the github actions.

https://github.com/changesets/action/blob/main/action.yml#L27-L30

Please consider this!

**Comment by u-yas** [comment]
As an example, when you publish a release note, the following notification will be displayed on the github home screen

<img width="872" alt="スクリーンショット 2023-07-10 21 23 36" src="https://github.com/poteboy/kuma-ui/assets/52757302/dbc7bfc2-92dc-4a3b-9cb6-65750e9fbbc7">

**Comment by u-yas** [comment]
If the automatic generation doesn't work, you can also manually publish the release notes in the beginning.
Github will automatically create a release note if you select association with tags etc.


※Image is my hobby project

[Go to this page](https://github.com/poteboy/kuma-ui/releases) and you should see a button for "draft a new release"
<img width="1280" alt="スクリーンショット 2023-07-10 21 31 48" src="https://github.com/poteboy/kuma-ui/assets/52757302/227ee621-cfaf-4cf9-9611-ef9948f5d296">

If you select "choose a tag", a list of git tags will be displayed. Press the "Generate Release note" button to automatically generate a release note
<img width="1355" alt="スクリーンショット 2023-07-10 21 32 29" src="https://github.com/poteboy/kuma-ui/assets/52757302/32f10f88-32d7-4aba-adfb-bdaa4e57b5d3">

**Comment by poteboy** [comment]
@u-yas  Thanks for rising this issue!  @kotarella1110 is working on this rn

**Comment by kotarella1110** [comment]
This issue has been resolved 🎉
