### ISSUE TITLE
Responsive Grid Template Columns throws error

### ISSUE THREAD

**Issue by iwatakeshi** [poteboy/kuma-ui#215]
Hi, I'm trying kuma-ui in a Next.js app and I seem to be getting an error when I use a `Grid` component's `gridTemplateColumns` property and pass an array to it:

```tsx
<Grid gridTemplateColumns={[
  'repeat(1, 1fr)',
  'repeat(2, 1fr)',
  'repeat(3, 1fr)',
]}>
 { /* ... */ }
</Grid>
```

The error message I get is:
```
- error ./app/page.tsx
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Array.map (<anonymous>)
    at Array.reduce (<anonymous>)
Import trace for requested module:
./app/page.tsx

```

Is this the correct behavior? I've attached a reproducible if that makes things easier for you.
[kuma-ui-repro.zip](https://github.com/poteboy/kuma-ui/files/12043363/kuma-ui-repro.zip)

By the way, awesome library. Please keep up the good work!

**Comment by poteboy** [comment]
Hi @iwatakeshi ,

We've made a fix for this issue in PR #216 , which should resolve the error you're seeing when passing an array to the `gridTemplateColumns` property of the Grid component.

I would also like to thank you for providing a reproducible example, it helps me address these issues more effectively.

**Comment by iwatakeshi** [comment]
@poteboy Thank you very much!

**Comment by poteboy** [comment]
New verision now available! Let me know if anything goes wrong!
@iwatakeshi

**Comment by iwatakeshi** [comment]
@poteboy Thank you! Will do!
