### ISSUE TITLE
Good place for unit test dir

### ISSUE THREAD

**Issue by Kazuhiro-Mimaki** [poteboy/kuma-ui#218]
As far as I can see, test files are in the same directory with the script files.
How about replacing the test files in some directory?

For example
- setup `__tests__` directories
- colocation (src/hoge/hoge.ts, src/hoge/hoge.test.ts)

**Comment by masa5555** [comment]
What are the benefits?

**Comment by poteboy** [comment]
Thank you for raising this issue!
However, my preference leans towards keeping the test files as close as possible to the actual implementation. Consequently, I will not be acting on this particular request and will have to close the issue. I appreciate your understanding 🙏
