### ISSUE TITLE
Home page banner text is not visible correctly.

### ISSUE THREAD

**Issue by Starboy-Sharma** [poteboy/kuma-ui#220]
Please check the image below. As you can see header text is not clearly visible.

I am using Firefox browser version 115.0.2 (64-bit). The same issue also exists in the Chrome browser as well.

![image](https://github.com/poteboy/kuma-ui/assets/31812684/ec82bec4-8ded-4e6c-934c-bcce82b0025b)

**Comment by poteboy** [comment]
it's now fixed!

<img width="946" alt="スクリーンショット 2023-07-16 14 35 17" src="https://github.com/poteboy/kuma-ui/assets/59927325/0a3889e1-bd7d-4901-81aa-307d50089b71">
