### ISSUE TITLE
Unable to start website dev server

### ISSUE THREAD

**Issue by DerTimonius** [poteboy/kuma-ui#226]
Hi everyone!

 I noticed some issues in the Docs page, where components are not really visible in dark mode (like mentioned in #221). I wanted to work on that, but after forking the repo, cloning it locally, running `pnpm install` and running the `dev` script in the website directory, I got the following error:
 ```
- error Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Cannot find module '/Users/DerTimonius/Coding/OpenSource/kuma-ui/website/node_modules/@kuma-ui/next-plugin/dist/index.js'
```

I was wondering if this is an issue with the monorepo and a missing `transpilePackages` in the next.config.js file or if there is another step in the setup that I missed?

**Comment by poteboy** [comment]
@DerTimonius 

Thank you for your interest in contributing to Kuma. It seems I might have missed mentioning this step in our `CONTRIBUTING.md`. After running `pnpm install`, you should also run `pnpm build`. This should compile the necessary packages and resolve your issue.

**Comment by DerTimonius** [comment]
Thank you, this helped!
