### ISSUE TITLE
rename - kuma ui  to something else anon

### ISSUE THREAD

**Issue by dennohpeter** [poteboy/kuma-ui#234]
I kindly request that you consider renaming this sound library to something else: ' kuma` as I understand in Japanese means `bear` but that might not be well-received in East Africa and across regions in Africa that speak `Swahili`,  little Google search or translation will add more context to this. thank you. ✌️

**Comment by poteboy** [comment]
Thank you for bringing this to our attention. Language and cultural differences can indeed be complex in our globalized world. The name ‘Kuma’ was chosen for its significance in Japanese, meaning ‘bear’, symbolizing the strength and reliability that we aim for in our library. Furthermore, **in Japan, there are many people named ‘Kuma’, which further indicates the respect and reverence associated with this word in our culture.** Changing the name could inadvertently cause distress to these individuals. 
We understand that words can have different meanings in different cultures. Please note that any unintended associations or interpretations in other languages are purely coincidental and not reflective of our intentions. We are committed to fostering a respectful and inclusive environment for all users, and we will seriously consider your feedback. We appreciate your understanding and respect for the cultural significance of ‘Kuma’ in Japanese culture, just as we respect the significance of words in other cultures. Your feedback is invaluable in this regard, and we sincerely thank you for it.
