### ISSUE TITLE
Global CSS import causes build error in Next.js

### ISSUE THREAD

**Issue by poteboy** [poteboy/kuma-ui#27]
In Next.js, the internal module bundler uses webpack. Kuma UI's next-plugin depends on `@kuma-ui/webpack-plugin`, which is implemented as a webpack loader and plugin.

The loader generates an external CSS file for each component that uses `@kuma-ui/core` and imports it using a relative path. This works fine for standard Webpack + React applications, but Next.js prohibits the import of global CSS in files other than the custom App component. As a result, a build error occurs during the build process:

> Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.js.
Read more: https://err.sh/next.js/css-global

This is a known issue, and we would like to create an issue in advance to address it. Any feedback or suggestions for resolving this issue would be greatly appreciated.

**Comment by yodakaEngineer** [comment]
Maybe, If update Next.js of example, it is resolved in App Router.
But, it's not resolved in Pages Router.

https://nextjs.org/blog/next-13-4#zero-setup-use-the-filesystem-as-an-api

> Previously, you could only import global stylesheets from external npm packages (like component libraries) in _app.js. This was a less-than-ideal developer experience. With the App Router, you can import (and colocate) any CSS file in any component.

**Comment by poteboy** [comment]
#43 could potentially solve this

**Comment by poteboy** [comment]
we close this issue as #44 replaces runtime injection with virtual loader.
